version: "3"
services:
  db:
    image: mariadb:latest
    container_name: pwp-test-db
    restart: always
    volumes:
      - pwp-mariadb-data:/var/lib/mysql
      - ./sql/init.sql:/init/init.sql
    command: "mysqld --init-file /init/init.sql"
    ports:
      - 6969:3306
    environment:
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
      MYSQL_ROOT_PASSWORD: test
      TZ: Europe/Helsinki

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pwp-mariadb-data: